import type { Metadata } from "next";
import { ThemeProvider } from "@/components/contexts/theme-provider";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Aria Docs Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="sm:container mx-auto w-[90vw] lg:w-[70vw] h-auto scroll-smooth">
          {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
